on:
  push:
    branches: [ master ]

jobs:
  hello_world_job_public:
    runs-on: ubuntu-latest
    name: test task public run

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Redoc and Speccy petstore.yml
        id: redoc_speccy_petstore
        uses: therealagentk/redoc-cli-speccy-action@1.2.1
        with:
          redoc-args: 'bundle test/petstore.yml -o redoc-output-petstore.html'
          speccy-args: 'resolve -o speccy-output-petstore.yml test/petstore.yml'

      - name: Check result
        run: |
          ls -al
          (test -f redoc-output-petstore.html && test -f speccy-output-petstore.yml) || (echo "Missing an output file from previous step." && exit 1)

      - name: Get the output time
        run: echo "The time was ${{ steps.redoc_speccy_petstore.outputs.time }}"

  hello_world_job_private:
    runs-on: ubuntu-latest
    name: test task private run
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Redoc and Speccy petstore.yml
        id: redoc_speccy_petstore
        uses: ./ # Uses an action in the root directory
        with:
          redoc-args: 'bundle test/petstore.yml -o redoc-output-petstore.html'
          speccy-args: 'resolve -o speccy-output-petstore.yml test/petstore.yml'

      - name: check result
        run: |
          ls -al
          (test -f redoc-output-petstore.html && test -f speccy-output-petstore.yml) || (echo "Missing an output file from previous step." && exit 1)

      - name: Get the output time
        run: echo "The time was ${{ steps.redoc_speccy_petstore.outputs.time }}"

